### ISSUE TITLE
Configuration file not parsed

### ISSUE THREAD

**Issue by bartekbrzezinski** [marcinbudny/ravendb_exporter#2]
Contrary to the README, namsral/flag and thus RavenDB Exporter does not parse a config file by default. There has to be a "config" flag defined. Trying to run ravendb_exporter with namsral/flag's default -config parameter ends with error:
```
$ ./ravendb_exporter -config ./ravendb_exporter.conf
flag provided but not defined: -config
Usage of ./ravendb_exporter:
(...)
```

I have used that default in #1 . If this PR is merged, the documentation can be amended by usage example, like this:
`ravendb_exporter -config ./ravendb_exporter.conf`

**Comment by marcinbudny** [comment]
PR accepted
