### ISSUE TITLE
"failed to parse private key" error on loading password-protected client key

### ISSUE THREAD

**Issue by bartekbrzezinski** [marcinbudny/ravendb_exporter#3]
When trying to run ravendb_exporter with auth enabled and CA and client certs configured and client key that is password-protected, it fails to start with following error:
```
$ ./ravendb_exporter -config ./ravendb_exporter.conf
INFO[0000] RavenDB exporter configured                   caCert=/opt/ravendb_exporter/cacert.crt clientCert=/opt/ravendb_exporter/admin.crt clientKey=/opt/ravendb_exporter/admin.key port=9440 ravenDbUrl="https://ravendb-01.gp.local:8080" timeout=10s useAuth=true verbose=false
FATA[0000] tls: failed to parse private key
```
When using client key without password, it runs as expected. 

Using password-protected client key is default in RavenDB and it's generally a good practice. There is no way to provide client key password in ravendb_exporter.

**Comment by marcinbudny** [comment]
Resolved in version 0.3.0 via `-client-key-password` flag.
