### ISSUE TITLE
compatible to ravendb5.4

### ISSUE THREAD

**Issue by florianow** [marcinbudny/ravendb_exporter#4]
Hey, 

i used your project to get the metrics of ravendb 5.4 and it still works without any changes of your Code. I found not much alternatives to your Project to grap the Metrics that are still available in the free version. Is it possible that you update Project the could using a newer image with updated versions from the container side (golang image busybox etc.)?

thanks for your work so far!
Cheers

**Comment by marcinbudny** [comment]
Hi, 
Sorry for the late reply. I updated go version, docker image and most of the dependencies. The prometheus client lib however cannot be updated without significant code changes, so I skipped it for now. The new version 0.4.0 is available on dockerhub.

**Comment by florianow** [comment]
hey, thanks a lot :)
